
credentials:
  login: 'cisco'
  password: 'cisco'

commands:
  - 'ntp server 8.8.8.8'
  - 'timezone GMT 0'

devices:
  sw1:
    ip: '192.168.1.201'
    device_type: 'cisco_xe'
  sw2:
    ip: '192.168.1.202'
    device_type: 'cisco_xe'
  sw3:
    ip: '192.168.1.203'
    device_type: 'cisco_xe'
  sw4:
    ip: '192.168.1.204'
    device_type: 'cisco_xe'
